name: Auto Commit

on:
  schedule:
    - cron: "50 18 * * *"  # Runs at 00:50 Dhaka Time (18:50 UTC)
    - cron: "05 19 * * *"  # Runs at 00:05 Dhaka Time (18:50 UTC)
    - cron: "0 17 * * *"  # 11:00 PM Dhaka Time (17:00 UTC)
    - cron: "45 16 * * *"  # 10:45 PM Dhaka Time (17:00 UTC)

  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
    # Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up Git (configure name and email)
    - name: Set Up Git
      run: |
        git config --global user.name "TahmidRaven"
        git config --global user.email "raven.of.the.endless@gmail.com"

    # Write to AutoRaven.md
    - name: Write to AutoRaven.md
      run: |
        DATE=$(TZ=Asia/Dhaka date +"%Y-%m-%d %H:%M:%S")  # Get exact timestamp in Dhaka Time
        echo -e "\nAutomated commit at $DATE (Dhaka Time)" >> AutoRaven.md  # Ensure newline before writing
        git add AutoRaven.md  # Stage the change


    # Check the Git status and diff (for debugging)
    - name: Check Git Status
      run: |
        git status
        git diff AutoRaven.md  # Check what has changed in the AutoRaven.md file

    # Commit and Push
    - name: Commit and Push
      run: |
        DATE=$(TZ=Asia/Dhaka date +"%Y-%m-%d %H:%M:%S")  # Get exact timestamp in Dhaka Time
        git commit -m "Automated commit at $DATE (Dhaka Time)" || exit 0  # Avoid error if no changes
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} main
